# Generated by Django 3.1.3 on 2020-12-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CantinaLeul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='job',
            field=models.CharField(choices=[('Designer', 'Designer'), ('Manager', 'Manager'), ('Accountant', 'Accountant')], max_length=100, null=True),
        ),
    ]
