# Generated by Django 3.1.3 on 2020-12-26 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CantinaLeul', '0002_newuser_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='newProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100, null=True)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ingrediente', models.CharField(max_length=300, null=True)),
                ('alergeni', models.CharField(max_length=300, null=True)),
                ('observatii', models.CharField(max_length=300, null=True)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('bucatar', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
