# Generated by Django 3.1.3 on 2020-12-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CantinaLeul', '0006_auto_20201227_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproduct',
            name='comandat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cos',
            name='produse',
            field=models.ManyToManyField(to='CantinaLeul.newProduct'),
        ),
        migrations.DeleteModel(
            name='produsComandat',
        ),
    ]
