# Generated by Django 3.1.3 on 2020-12-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CantinaLeul', '0007_auto_20201227_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cos',
            name='dataComandare',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='cos',
            name='produse',
            field=models.ManyToManyField(null=True, to='CantinaLeul.newProduct'),
        ),
    ]
