# Generated by Django 3.1.3 on 2020-12-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CantinaLeul', '0008_auto_20201227_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cos',
            name='produse',
        ),
    ]
