# Generated by Django 3.1.3 on 2020-12-27 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CantinaLeul', '0009_remove_cos_produse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cos',
            name='client',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='produse',
        ),
        migrations.AddField(
            model_name='cos',
            name='produse',
            field=models.ManyToManyField(blank=True, to='CantinaLeul.newProduct'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='cos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CantinaLeul.cos'),
        ),
    ]
