# Generated by Django 3.1.3 on 2020-12-27 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CantinaLeul', '0011_auto_20201227_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproduct',
            name='comandat',
        ),
        migrations.AddField(
            model_name='newproduct',
            name='stoc',
            field=models.IntegerField(default=1, max_length=3),
        ),
        migrations.CreateModel(
            name='orderedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comandat', models.BooleanField(default=False)),
                ('cantitate_comandata', models.IntegerField(default=1)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CantinaLeul.newproduct')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CantinaLeul.newuser')),
            ],
        ),
        migrations.AlterField(
            model_name='cos',
            name='produse',
            field=models.ManyToManyField(blank=True, to='CantinaLeul.orderedItem'),
        ),
    ]
