# Generated by Django 3.1.3 on 2020-12-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CantinaLeul', '0013_auto_20201227_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='facultate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='nr_matricol',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='nr_telefon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='nume',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
