# Generated by Django 3.1.3 on 2021-01-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CantinaLeul', '0014_auto_20201227_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='abonament',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newuser',
            name='prenume',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='reducere',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newuser',
            name='tip',
            field=models.CharField(choices=[('student', 'student'), ('profesor', 'profesor')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newproduct',
            name='stoc',
            field=models.IntegerField(default=1),
        ),
    ]
