# Generated by Django 3.1.3 on 2021-01-05 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CantinaLeul', '0016_newuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='newChef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('nume', models.CharField(max_length=100, null=True)),
                ('prenume', models.CharField(max_length=100, null=True)),
                ('imagine', models.ImageField(null=True, upload_to='profiluri')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
