# Generated by Django 3.1.3 on 2021-01-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CantinaLeul', '0017_newchef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newchef',
            name='email',
        ),
    ]
