# Generated by Django 3.1.3 on 2021-01-05 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CantinaLeul', '0018_remove_newchef_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='cerere_abonament',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newuser',
            name='data_expirare',
            field=models.DateField(default=datetime.date(2021, 1, 5)),
        ),
    ]
