# Generated by Django 3.1.3 on 2021-01-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CantinaLeul', '0019_auto_20210105_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='newLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locatie', models.CharField(max_length=300)),
            ],
        ),
    ]
