# Generated by Django 3.1.3 on 2021-01-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CantinaLeul', '0020_newlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='newContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locatie', models.CharField(max_length=300, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('numele_strazii', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='newLocation',
        ),
    ]
